[config]
schemaVersion = "0.0.1"

[package]
namespace = "Gogas1"
name = "ExampleModifierMod"
versionNumber = "0.1.0"
description = "your mod description"
websiteUrl = "link to the git repo"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"Gogas1-BossChallengeMod" = "3.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
